// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrRTA2vH5ZbJFc5Zs4pq30YxDrJez8nxA',
    appId: '1:94268790412:web:fe43d09b9223126ad18da9',
    messagingSenderId: '94268790412',
    projectId: 'pharmaceutical-hackathon',
    authDomain: 'pharmaceutical-hackathon.firebaseapp.com',
    storageBucket: 'pharmaceutical-hackathon.firebasestorage.app',
    measurementId: 'G-ZKMCX33FQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYgeesSI9dxCNsvg30EoJMnoxDZjK7qVo',
    appId: '1:94268790412:android:c4e74f8fb6171f9bd18da9',
    messagingSenderId: '94268790412',
    projectId: 'pharmaceutical-hackathon',
    storageBucket: 'pharmaceutical-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvQ-RVXXSvhoT_Z1xTrk1ZU-3OEUWwFGg',
    appId: '1:94268790412:ios:b4ee0fb37a8c3e38d18da9',
    messagingSenderId: '94268790412',
    projectId: 'pharmaceutical-hackathon',
    storageBucket: 'pharmaceutical-hackathon.firebasestorage.app',
    iosBundleId: 'com.tomate.tomate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvQ-RVXXSvhoT_Z1xTrk1ZU-3OEUWwFGg',
    appId: '1:94268790412:ios:b4ee0fb37a8c3e38d18da9',
    messagingSenderId: '94268790412',
    projectId: 'pharmaceutical-hackathon',
    storageBucket: 'pharmaceutical-hackathon.firebasestorage.app',
    iosBundleId: 'com.tomate.tomate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrRTA2vH5ZbJFc5Zs4pq30YxDrJez8nxA',
    appId: '1:94268790412:web:655b529cf6e54c2fd18da9',
    messagingSenderId: '94268790412',
    projectId: 'pharmaceutical-hackathon',
    authDomain: 'pharmaceutical-hackathon.firebaseapp.com',
    storageBucket: 'pharmaceutical-hackathon.firebasestorage.app',
    measurementId: 'G-H00WNN41QR',
  );
}
